# Generated by Django 4.2.1 on 2023-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('weight', models.FloatField()),
                ('size', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('processorBrand', models.CharField(max_length=50)),
                ('processorModel', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('storageType', models.CharField(max_length=10)),
                ('storageMemory', models.IntegerField()),
                ('batteryLife', models.IntegerField()),
                ('graphicsCardBrand', models.CharField(max_length=50)),
                ('graphicsCardModel', models.CharField(max_length=50)),
                ('graphicsMemory', models.IntegerField()),
                ('screenQuality', models.TextField()),
                ('os', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
                ('extraInfo', models.TextField()),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('amazonLink', models.URLField()),
                ('flipkartLink', models.URLField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
    ]
