# Generated by Django 4.2.1 on 2023-06-15 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laptops', '0002_alter_laptop_storagememory'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='user_favourite',
            field=models.ManyToManyField(blank=True, related_name='user_favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
