# Generated by Django 4.2.1 on 2023-08-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_laptop_user_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='storageSize',
            field=models.CharField(default='GB', max_length=50),
            preserve_default=False,
        ),
    ]
