# Generated by Django 4.2.1 on 2023-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_laptop_storagesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='storageMemory',
            field=models.IntegerField(),
        ),
    ]
